export const pow = Math.pow
export const sqrt = Math.sqrt
export const sin = Math.sin
export const cos = Math.cos
export const PI = Math.PI
export const c1 = 1.70158
export const c2 = c1 * 1.525
export const c3 = c1 + 1
export const c4 = (2 * PI) / 3
export const c5 = (2 * PI) / 4.5
